name: Windows Build

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: 플러터 세팅하기
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: 패키지 다운로드
        run: flutter pub get

      - name: 윈도우 앱 아이콘 생성하기
        run: flutter pub run flutter_launcher_icons

      - name: 윈도우 앱 빌드하기 (.exe 생성)
        run: flutter build windows

      - name: 완성된 파일 업로드 (다운로드용)
        uses: actions/upload-artifact@v4
        with:
          name: Todays_Library_Windows
          path: build\windows\x64\runner\Release\